shell = 'zsh'

apply = ["defer"]

[plugins]
[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.dotfiles-defers]
local = "~/dotfiles/zsh-defer"
use = ["{!sync,*}.zsh"]
